name: Run Tests, Build App, Publish Library

on:
  push:
    branches:
      - "*"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Checkout Submodules
      uses: actions/checkout@v4

    - name: Run Lint
      run: ./gradlew lint --console plain
    - name: Run Unit Tests
      run: ./gradlew test --console plain

    - name: Publish Library
      run: ./gradlew :library:publish --info

    - name: Build Example App
      run: ./gradlew :example:assembleRelease
